// Generated by PInvoke Wizard (v 1.0) from The Paul Yao Company http://www.paulyao.com 

using System;
using System.Drawing;

namespace GapiDrawNet
{
	public struct GDRect
	{
		public GDRect(int left, int top, int right, int bottom)
		{
			Left = left;
			Top = top;
			Right = right;
			Bottom = bottom;
		}
		
        public int Left;
		public int Top;
		public int Right;
		public int Bottom;

        public int Height
        {
            get { return Bottom - Top; }
            set { Bottom = Top + value; }
        }

        public int Width
        {
            get { return Right - Left; }
            set { Right = Left + value; }
        }

		public bool Contains(Point p)
		{
			return (p.X >= Left) && (p.X <= Right) && (p.Y >= Top) && (p.Y <= Bottom);
		}
		public bool Contains(int x, int y)
		{
			return (x >= Left) && (x <= Right) && (y >= Top) && (y <= Bottom);
		}

		public void Inflate(int inflateBy)
		{
			Left-= inflateBy;
			Top -= inflateBy;
			Right += inflateBy;
			Bottom += inflateBy;
		}

        public static GDRect FromRectangle(Rectangle rect)
        {
            return new GDRect(rect.Left, rect.Top, rect.Right, rect.Bottom);
        }

        public static implicit operator Rectangle(GDRect rect)
        {
            return new Rectangle(rect.Left, rect.Top, rect.Right - rect.Left, rect.Bottom - rect.Top);
        }

        public static implicit operator GDRect(Rectangle rect)
        {
            return new GDRect(rect.X, rect.Y, rect.Right, rect.Bottom);
        }
	}
}